### ISSUE TITLE
Multiple Repsitory issue with version 8.3

### ISSUE THREAD

**Issue by PilotBob** [versionone/VersionOne.Integration.Subversion#31]
I am moving from an older version to 8.3. 

Does this no longer correctly work with multiple repositories. I previously have 

SvnReaderService1 and SvnRederService2 configured. 

I attempted SvnReaderService1 and SvnReaderService2 as well as SvnReaderHostedService1/2.

According to the console log, It seems to only initialize 1, and it even reads the config for Reader2 from the profile.xml as Reader1 and rewrites it. 

I would attempt to debug but I can not build a get from Master.

Also, I created WriterService1 and WriterService2... the console log does show them both instantiated.

That all said, is it possible to run two instances on the save server? If so, how could I do that?

**Comment by danielgruesso** [comment]
Hi PilotBob - we have not tested with 8.3.  What happens when you attempt to get a build from Master? We have not tested multiple instances on the same server.

**Comment by PilotBob** [comment]
I was unable to get the correct dependencies. Versions specified in the packages.config didn't exist in the nuget feed... I changed the dependency to a newer version (not current just as close to what we referenced as possible) and still got build errors.

I gave up after that and decided to stick with the older version I was running which is working with multi repositories without issue.

**Comment by danielgruesso** [comment]
Sorry to hear that. I've added this to our backlog so it can be addressed in the future.
